Adding exceptions when RoO files cannot be found
uktrade/dit-helpdesk pull request #543
Opened 2021-07-21 08:30 UTC by Santino-Trade

2021-07-28 11:19 UTC, kevincarrogan requested changes

2021-07-28 11:19 UTC, kevincarrogan commented on dit_helpdesk/rules_of_origin/ingest/importer.py
> +
I think we should remove this global and do this in a different way. I've noted more in this review where I think we could change this.

2021-07-28 11:19 UTC, kevincarrogan commented on dit_helpdesk/rules_of_origin/management/commands/import_rules_of_origin.py
> +                        )
When doing logging.<type> calls you shouldn't do your own string formatting/interpolation.

The right way to do this is:
`logger.info("Local import file %s is not an XML file, skipping to next file.", filename)`

The reason behind this is that logging calls may or may not happen depending on how logging is configured and the string evaluation is something that could be skipped if the logging call is configured not to output.

2021-07-28 11:19 UTC, kevincarrogan commented on dit_helpdesk/rules_of_origin/management/commands/import_rules_of_origin.py
> +                        )
When doing logging.<type> calls you shouldn't do your own string formatting/interpolation.

The right way to do this is:
`logger.info("Local import file %s is not an XML file, skipping to next file.", filename)`

The reason behind this is that logging calls may or may not happen depending on how logging is configured and the string evaluation is something that could be skipped if the logging call is configured not to output.

2021-07-28 11:19 UTC, kevincarrogan commented on dit_helpdesk/rules_of_origin/management/commands/import_rules_of_origin.py
> +        )
See other comment about logging calls.

2021-07-28 11:19 UTC, kevincarrogan commented on dit_helpdesk/rules_of_origin/tests/test_importer.py
> +test_data_path_empty = os.path.join(apps_dir, "rules_of_origin", "ingest", "data")
This directory is actually not empty on my local machine so I think we should make a new folder that is explicitly empty just for this purpose.

2021-07-28 11:19 UTC, kevincarrogan commented on dit_helpdesk/rules_of_origin/tests/test_importer.py
> +        rules_of_origin.ingest.importer.countries_with_docs = ["XT"]
Instead of tweaking the `countries_with_docs` variable here I think we should decouple the test from the implementation and actually just have a test directory with two files that have the same countries in them.

2021-07-28 13:46 UTC, Santino-Trade commented on dit_helpdesk/rules_of_origin/ingest/importer.py
> +
Changed how we go about this to start using a DB query instead

2021-07-29 10:13 UTC, kevincarrogan approved these changes

2021-07-29 10:13 UTC, kevincarrogan commented on dit_helpdesk/rules_of_origin/ingest/importer.py
> +        existing_rules_document = RulesDocument.objects.filter(countries=country)
Make this:

existing_rules_document = RulesDocument.objects.filter(countries=country, nomenclature_tree=nomenclature_tree)

2021-07-29 11:38 UTC, merged