Moving reload_data steps to Python command
uktrade/dit-helpdesk pull request #606
Opened 2021-11-04 13:54 UTC by Santino-Trade

2021-11-04 14:57 UTC, kevincarrogan requested changes

2021-11-04 14:57 UTC, kevincarrogan commented on dit_helpdesk/core/management/commands/reload_data.py
> +            )
I think this should be logger.error and possibly the the exception should be re-raised.

At the very least this script needs to return a sys exit of some kind of error when this happens.

2021-11-04 14:57 UTC, kevincarrogan commented on dit_helpdesk/core/management/commands/reload_data.py
> +            )
Also, logging formatting should be done differently.

https://docs.python.org/3/howto/logging.html#logging-variable-data

2021-11-04 14:57 UTC, kevincarrogan commented on dit_helpdesk/core/management/commands/reload_data.py
> +            )
Also, logging formatting should be done differently.

https://docs.python.org/3/howto/logging.html#logging-variable-data

2021-11-04 14:57 UTC, kevincarrogan commented on dit_helpdesk/core/management/commands/reload_data.py
> +            )
Also, logging formatting should be done differently.

https://docs.python.org/3/howto/logging.html#logging-variable-data

2021-11-04 14:57 UTC, kevincarrogan commented on dit_helpdesk/core/models.py
> +    reason = models.CharField(null=True, max_length=255)
This should probably be a `TextField`

2021-11-04 14:57 UTC, kevincarrogan commented on dit_helpdesk/core/models.py
> +    reason = models.CharField(null=True, max_length=255)
This should probably be a `TextField`

2021-11-04 15:42 UTC, Santino-Trade commented on dit_helpdesk/core/models.py
> +    reason = models.CharField(null=True, max_length=255)
Do you think the length will be ok?

2021-11-04 15:53 UTC, kevincarrogan commented on dit_helpdesk/core/models.py
> +    reason = models.CharField(null=True, max_length=255)
If you use a `TextField` then you don't need to worry about the length (which is why I think it's better to use that instead).

2021-11-11 16:52 UTC, kevincarrogan requested changes

2021-11-11 16:52 UTC, kevincarrogan commented on dit_helpdesk/core/management/commands/reload_data.py
> +        reload_data_fail_arg = "FAILURE in " + step + " - " + error
Use f-strings everywhere except for `logging`.

2021-11-11 16:52 UTC, kevincarrogan commented on dit_helpdesk/core/management/commands/reload_data.py
> +            f"--reason='{reload_data_fail_arg}'",
Could there be some weird escaping issues here if the failure arg has some text in it that the command line would read or does `call_command` handle that?

2021-11-11 16:52 UTC, kevincarrogan commented on dit_helpdesk/core/management/commands/reload_data.py
> +            f"--reason='{reload_data_fail_arg}'",
I don't think exceptions should have side effects i.e. it shouldn't be calling this code. Think about the case where this `call_command` might cause an exception and then you're in a weird situation of raising an exception causing an exception itself.

2021-11-25 12:19 UTC, Santino-Trade commented on dit_helpdesk/core/management/commands/reload_data.py
> +            f"--reason='{reload_data_fail_arg}'",
Any that you're worried about in particular? I just raised this fake error to test:
`raise CommandError("Testing an escape character: '\" \" \n this should still be raised here...\\")`
got this in the terminal:
`core.management.commands.reload_data.ReloadDataException: "reload_data script has failed during the progress_track start step with the following error: Testing an escape character: '" " 
 this should still be raised here...\`
and this is what ended up in the db table:
`'FAILURE in progress_track start - Testing an escape character: '" " + this should still be raised here...'`

2021-11-25 13:40 UTC, kevincarrogan commented on dit_helpdesk/core/management/commands/reload_data.py
> +            f"--reason='{reload_data_fail_arg}'",
You're right, I was thinking that somehow someone might be able to terminate the reason string in some way and run arbitrary commands but it looks like something is escaping it along the way. However, `call_command` does just allow you to pass in the arguments as normal keyword arguments directly e.g.

```
call_command(
    "progress_track",
    end_reload_data=True,
    reason="This is the reason",
)
```

2021-11-25 14:00 UTC, kevincarrogan commented on dit_helpdesk/core/management/commands/reload_data.py
> +            reload_data_fail_arg = f"FAILURE in {current_step} - {str(e)}"
You don't need to do `str` in here because the f-string is already doing that for you (this is why f-strings are good).

2021-11-25 14:01 UTC, kevincarrogan approved these changes

2021-11-26 11:23 UTC, merged